// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sellius.API.Infra.Context;

#nullable disable

namespace Sellius.API.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514192951_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sellius.API.Domain.Entity.City", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint")
                        .HasColumnName("state_id");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.HasIndex("StateId")
                        .HasDatabaseName("ix_city_state_id");

                    b.ToTable("city", (string)null);
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<long?>("GroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<long?>("SegmentationId")
                        .HasColumnType("bigint")
                        .HasColumnName("segmentation_id");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_customers_city_id");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_customers_enterprise_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_customers_group_id");

                    b.HasIndex("SegmentationId")
                        .HasDatabaseName("ix_customers_segmentation_id");

                    b.ToTable("Customers", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.GroupCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_group_customers");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_group_customers_enterprise_id");

                    b.ToTable("GroupCustomers", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.Segmentation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_segmentations");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_segmentations_enterprise_id");

                    b.ToTable("Segmentations", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("LicencaId")
                        .HasColumnType("uuid")
                        .HasColumnName("licenca_id");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uuid")
                        .HasColumnName("license_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_enterprise");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_enterprise_city_id");

                    b.HasIndex("LicenseId")
                        .HasDatabaseName("ix_enterprise_license_id");

                    b.ToTable("Enterprise", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityEnterprises.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_price");

                    b.Property<decimal>("PriceForUser")
                        .HasColumnType("numeric")
                        .HasColumnName("price_for_user");

                    b.Property<int>("QtdeUserFree")
                        .HasColumnType("integer")
                        .HasColumnName("qtde_user_free");

                    b.Property<DateTime>("StartLicenseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_license_date");

                    b.Property<int>("TypeLicense")
                        .HasColumnType("integer")
                        .HasColumnName("type_license");

                    b.HasKey("Id")
                        .HasName("pk_license");

                    b.ToTable("license", (string)null);
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.PriceTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("DescPriceTable")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc_price_table");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<DateTime?>("FinalValidateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("final_validate_date");

                    b.Property<DateTime>("InitialValidateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initial_validate_date");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_price_tables");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_price_tables_enterprise_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_price_tables_supplier_id");

                    b.ToTable("PriceTables", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.PriceTableXProduct", b =>
                {
                    b.Property<long>("PriceTableId")
                        .HasColumnType("bigint")
                        .HasColumnName("price_table_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("PriceTableId", "ProductId")
                        .HasName("pk_price_table_x_products");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_price_table_x_products_product_id");

                    b.ToTable("PriceTableXProducts", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime?>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.Property<long?>("TypeProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("type_product_id");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_products_enterprise_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_products_supplier_id");

                    b.HasIndex("TypeProductId")
                        .HasDatabaseName("ix_products_type_product_id");

                    b.ToTable("Products", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.TypeProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_type_products");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_type_products_enterprise_id");

                    b.ToTable("TypeProducts", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.Authentication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_logins");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_logins_enterprise_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_logins_user_id");

                    b.ToTable("Logins", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime?>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("DescMenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc_menu");

                    b.Property<Guid?>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<long?>("MenuFatherId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_father_id");

                    b.Property<string>("UrlMenu")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url_menu");

                    b.HasKey("Id")
                        .HasName("pk_menus");

                    b.ToTable("Menus", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.TypeUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_type");

                    b.HasKey("Id")
                        .HasName("pk_type_users");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_type_users_enterprise_id");

                    b.ToTable("TypeUsers", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.TypeUserXMenu", b =>
                {
                    b.Property<long>("TypeUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("type_user_id");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("menu_id");

                    b.HasKey("TypeUserId", "MenuId")
                        .HasName("pk_type_user_x_menus");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("ix_type_user_x_menus_menu_id");

                    b.ToTable("TypeUserXMenus", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<long>("TpUsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("tp_usuario_id");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_user_city_id");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_user_enterprise_id");

                    b.HasIndex("TpUsuarioId")
                        .HasDatabaseName("ix_user_tp_usuario_id");

                    b.ToTable("User", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.UserConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("PermissionApprove")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_approve");

                    b.Property<bool>("PermissionControlUser")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_control_user");

                    b.Property<bool>("PermissionCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_create");

                    b.Property<bool>("PermissionDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_delete");

                    b.Property<bool>("PermissionEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_edit");

                    b.Property<bool>("PermissionExport")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_export");

                    b.Property<bool>("PermissionInactivate")
                        .HasColumnType("boolean")
                        .HasColumnName("permission_inactivate");

                    b.Property<long>("TypeUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("type_user_id");

                    b.Property<long?>("TypeUserId1")
                        .HasColumnType("bigint")
                        .HasColumnName("type_user_id1");

                    b.HasKey("Id")
                        .HasName("pk_user_configurations");

                    b.HasIndex("TypeUserId")
                        .HasDatabaseName("ix_user_configurations_type_user_id");

                    b.HasIndex("TypeUserId1")
                        .IsUnique()
                        .HasDatabaseName("ix_user_configurations_type_user_id1");

                    b.ToTable("UserConfigurations", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrdeXProduct", b =>
                {
                    b.Property<long>("SaleOrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<decimal>("PriveSeller")
                        .HasColumnType("numeric")
                        .HasColumnName("prive_seller");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.HasKey("SaleOrderId", "ProductId")
                        .HasName("pk_sale_order_x_product");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_order_x_product_product_id");

                    b.ToTable("SaleOrderXProduct", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<short>("Finished")
                        .HasColumnType("smallint")
                        .HasColumnName("finished");

                    b.Property<DateTime>("OrderCreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("order_create_date");

                    b.Property<int>("Qtd")
                        .HasColumnType("integer")
                        .HasColumnName("qtd");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sale_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sale_orders_customer_id");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_sale_orders_enterprise_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_sale_orders_user_id");

                    b.ToTable("SaleOrders", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.State", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acronym");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_states");

                    b.ToTable("States", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Active")
                        .HasColumnType("smallint")
                        .HasColumnName("active");

                    b.Property<DateTime>("AlteredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("altered_date");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint")
                        .HasColumnName("city_id");

                    b.Property<string>("Complement")
                        .HasColumnType("text")
                        .HasColumnName("complement");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EnterpriseId")
                        .HasColumnType("uuid")
                        .HasColumnName("enterprise_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_suppliers_city_id");

                    b.HasIndex("EnterpriseId")
                        .HasDatabaseName("ix_suppliers_enterprise_id");

                    b.ToTable("Suppliers", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.SupplierXCustomer", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasColumnName("supplier_id");

                    b.HasKey("CustomerId", "SupplierId")
                        .HasName("pk_supplier_x_customers");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_x_customers_supplier_id");

                    b.ToTable("SupplierXCustomers", "Sellius");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.City", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.State", "State")
                        .WithMany("Citys")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_city_state_state_id");

                    b.Navigation("State");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.Customer", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_city_city_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customers_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityCustomers.GroupCustomer", "Gruop")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("fk_customers_group_customer_group_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityCustomers.Segmentation", "Segmentation")
                        .WithMany()
                        .HasForeignKey("SegmentationId")
                        .HasConstraintName("fk_customers_segmentation_segmentation_id");

                    b.Navigation("City");

                    b.Navigation("Enterprise");

                    b.Navigation("Gruop");

                    b.Navigation("Segmentation");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.GroupCustomer", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_customers_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.Segmentation", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_segmentations_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_enterprise_city_city_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .HasConstraintName("fk_enterprise_license_license_id");

                    b.Navigation("City");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.PriceTable", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_tables_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_tables_supplier_supplier_id");

                    b.Navigation("Enterprise");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.PriceTableXProduct", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityProduct.PriceTable", "PriceTable")
                        .WithMany("PriceTableXProducts")
                        .HasForeignKey("PriceTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_table_x_products_price_tables_price_table_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityProduct.Product", "Produto")
                        .WithMany("PriceTableXProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_table_x_products_product_product_id");

                    b.Navigation("PriceTable");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.Product", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_supplier_supplier_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityProduct.TypeProduct", "TypeProduct")
                        .WithMany("Products")
                        .HasForeignKey("TypeProductId")
                        .HasConstraintName("fk_products_type_product_type_product_id");

                    b.Navigation("Enterprise");

                    b.Navigation("Supplier");

                    b.Navigation("TypeProduct");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.TypeProduct", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_products_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.Authentication", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_logins_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_logins_user_user_id");

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.TypeUser", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_users_enterprise_enterprise_id");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.TypeUserXMenu", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.Menu", "Menu")
                        .WithMany("TypeUserXMenus")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_user_x_menus_menus_menu_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.TypeUser", "TypeUser")
                        .WithMany("TypeUserXMenus")
                        .HasForeignKey("TypeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_user_x_menus_type_users_type_user_id");

                    b.Navigation("Menu");

                    b.Navigation("TypeUser");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.User", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_city_city_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.TypeUser", "TypeUser")
                        .WithMany()
                        .HasForeignKey("TpUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_type_users_tp_usuario_id");

                    b.Navigation("City");

                    b.Navigation("Enterprise");

                    b.Navigation("TypeUser");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.UserConfiguration", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.TypeUser", "TypeUser")
                        .WithMany()
                        .HasForeignKey("TypeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_configurations_type_users_type_user_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.TypeUser", null)
                        .WithOne("UserConfiguration")
                        .HasForeignKey("Sellius.API.Domain.Entity.EntityUsers.UserConfiguration", "TypeUserId1")
                        .HasConstraintName("fk_user_configurations_type_users_type_user_id1");

                    b.Navigation("TypeUser");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrdeXProduct", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityProduct.Product", "Product")
                        .WithMany("SaleOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_order_x_product_products_product_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrder", "SaleOrder")
                        .WithMany("Product")
                        .HasForeignKey("SaleOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_order_x_product_sale_order_sale_order_id");

                    b.Navigation("Product");

                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrder", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityCustomers.Customer", "Customer")
                        .WithMany("SaleOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_orders_customers_customer_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_orders_enterprise_enterprise_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityUsers.User", "User")
                        .WithMany("SaleOrder")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_orders_user_user_id");

                    b.Navigation("Customer");

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.Supplier", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_city_city_id");

                    b.HasOne("Sellius.API.Domain.Entity.EntityEnterprises.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_enterprise_enterprise_id");

                    b.Navigation("City");

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.SupplierXCustomer", b =>
                {
                    b.HasOne("Sellius.API.Domain.Entity.EntityCustomers.Customer", "Customer")
                        .WithMany("SupplierXCustomer")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_x_customers_customers_customer_id");

                    b.HasOne("Sellius.API.Domain.Entity.Supplier", "Supplier")
                        .WithMany("SupplierXCustomer")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_x_customers_suppliers_supplier_id");

                    b.Navigation("Customer");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityCustomers.Customer", b =>
                {
                    b.Navigation("SaleOrders");

                    b.Navigation("SupplierXCustomer");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.PriceTable", b =>
                {
                    b.Navigation("PriceTableXProducts");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.Product", b =>
                {
                    b.Navigation("PriceTableXProducts");

                    b.Navigation("SaleOrders");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityProduct.TypeProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.Menu", b =>
                {
                    b.Navigation("TypeUserXMenus");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.TypeUser", b =>
                {
                    b.Navigation("TypeUserXMenus");

                    b.Navigation("UserConfiguration");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntityUsers.User", b =>
                {
                    b.Navigation("SaleOrder");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.EntitysSaleOrder.SaleOrder", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.State", b =>
                {
                    b.Navigation("Citys");
                });

            modelBuilder.Entity("Sellius.API.Domain.Entity.Supplier", b =>
                {
                    b.Navigation("SupplierXCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
